- LFGBulletinBoard/Dungeons.lua
Changing vanilla dungeon ranges to be the same as the summoning stone requirements if running TBC
> Changing Vanilla Dungeon Ranges

- LFGBulletinBoard/GroupBulletinBoard.xml
`low` was causing the LFG window to appear below some unit frames.
> Bump frameStrata to high to avoid UI overlaps

- LFGBulletinBoard/bindings.xml
Allows quick window toggle from keybind.
Keybind can be set in Settings -> Key Bindings -> Other
> added bindings.xml for quick window toggle

- .gitignore
- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/changelog.txt
If you had "custom" selected in search patterns it wouldn't properly identify heroics. Fixed the issue
> Fix for heroic not properly identifed

- LFGBulletinBoard/Localization.lua
The official channel name in french is "RechercheDeGroupe" and not "RechercheGroupe"; using the wrong channel name has a side effect as joining it first and forces it to be channel number 1 (/1) - User can always join "RechercheGroupe" and check this channel in settings pannel to use it, but default channel must be the official one.
> Use official channel name in French

- LFGBulletinBoard/GroupBulletinBoard.lua
This allows the user to enable 'filter by level', and show heroics with low normal levels (such as Ramparts).
> Allowing heroic dungeons when filtering by level

- LFGBulletinBoard/GroupBulletinBoard.lua
This allows the user to enable 'filter by level', and show heroics with low normal levels (such as Ramparts).
Fixed an issue where low level characters would see heroic modes.
> Handling heroics for low level characters

- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/LfgToolList.lua
- LFGBulletinBoard/Localization.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/RequestList.lua
- LFGBulletinBoard/Tags.lua
With Season of Discovery both trade and LFG have been hammered with people advertising fast traveling services.  This change lets you separate those into their own category.  
It also brings a new checkbox that will prevent those services from showing up in the trade bulletin list or in a dungeon
For example, take the following message
> [2. Trade] WTS Summons for Scarlet Monastery - (GY LIB ARMORY CATH) 
**Good:** If you are looking for a SM summon: you would see this in trade bulletin or perhaps a SM bulletin
**Bad:** If you are trying to find an enchanter in the Trade bulletins this message would show up the trade bulletins (and there are _a lot_ of these summon services spamming)
**Bad:** If you are trying to find a SM LIB group this would show up in the SM LIB bulletins
**Good:** If …
> Allow better isolation of summoning services popular in SoD

- LFGBulletinBoard/LfgToolList.lua
- LFGBulletinBoard/LibGPIToolBox.lua
- LFGBulletinBoard/RequestList.lua
Related Issue:
- #209  
Removed any direct indexing of `RAID_CLASS_COLOR` in favor of `Addon.Tool.ClassColor`.
`Addon.Tool.ClassColor` now references the `CUSTOM_CLASS_COLOR` table when found.
> feat: add support for `CUSTOM_CLASS_COLORS` table

- LFGBulletinBoard/LibGPIToolBox.lua
- https://legacy.curseforge.com/wow/addons/lfg-group-finder-bulletin-board?comment=623
Taint occurs on line 61 where global table data was modified with `Tool.ClassColor[k] = v;` whenever `CUSTOM_CLASS_COLORS` existed.
> fix: `TableCopy` reference to global `RAID_CLASS_COLORS` to prevent taint.

- LFGBulletinBoard/GroupBulletinBoard.lua
- #224 
- #212 
Setting this value prevents the frame from being dragged/growing out of screen.
> fix: `SetClampedToScreen` to `true` for `GroupBulletinBoardFrame`

- LFGBulletinBoard/GroupBulletinBoard.lua
Fixes a ui issue with multiple overlapping scrollbars being always visible.
**Images**
(before & after)
> minor: hide unused `ScrollFrames` in classic

- LFGBulletinBoard/LibGPIToolBox.lua
The `SetRotation` function call was commented out in pull #183 along with the following:
> Commenting this out to avoid an LUA error. Has to do with rotation of the resize cursor, can't figure it out at the moment
I've had it un-commented for a couple of hours and havent ran into any errors yet.
Images:
> minor: `ResizeCursor` icon indicates grow direction again

- LFGBulletinBoard/Options.lua
- Followed by comment from https://github.com/Vysci/LFG-Bulletin-Board/pull/227
- The quick access setting on the minimap is misplaced and should be relocated to the regular settings, as it's not an option that needs to be frequently changed.
- And it has been mentioned how to reset the window with command ```/gbb reset``` in about section in the regular settings, it might still be hard for users to find.
- Used GlobalStrings "RESET_POSITION": https://github.com/Vysci/LFG-Bulletin-Board/pull/230#issuecomment-2094916287
Code changed
- Added button on the bottom of the regular setting menu
Test
- Click on "Reset Position" button on the regular setting menu
1. Reseted ether opened or closed window.
2. Close popup-menu after close.
3. No Lua error caused.
- in the other locale(Korean)
> Added reset position button on the regular setting

- LFGBulletinBoard/GroupBulletinBoard.lua
Fixes a small visual issue where the `/gbb reset` or `Reset Position` button would over-shrink the window causing the searchbar to overflow
**Images**:
(Before)
(After)
> fix: update hardcoded sizing in `GBB.ResetWindow`

- LFGBulletinBoard/Dungeons.lua
Moves `ONY` key from `WotlkDungeonNames` to the `VanillDungeonNames` table.
This bug was introduced in Vysci/LFG-Bulletin-Board#219 since `ONY` was not included in the `GBB.VanillDungeonNames`
**images**
(before)
(after)
> hotfix: Add `ONY` to classic era

- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/LfgToolList.lua
- LFGBulletinBoard/LibGPIOptions.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/Tags.lua
- LFGBulletinBoard/dungeons/cata.lua
- LFGBulletinBoard/dungeons/classic.lua
These modules enable us to organize dungeon-related data according to the client being used.
Data is obtained using the `GetLFGDungeonInfo` and `GetActivityInfoTable` WoW API's and sourced `LFGDungeon` and `GroupFinderActivity` Ids for the two clients. 
Any data that either, cannot be obtained using the mentioned APIs, or needs modification from what is provided by the game API can be added in the `infoOverrides` table.
You can find the modules in the `/LFGBulletinBoard/dungeons/` directory. There are `cata.lua` and `classic.lua` files for the "Cataclysm Classic" and "Classic Era" clients, respectively.
- [classic era](https://github.com/Vysci/LFG-Bulletin-Board/pull/236/commits/82f920fab1ddc8312b3d5091aedb9307db56268d)
- [cataclysm](https://github.com/Vysci/LFG-Bulletin-Board/pull/236/com …
> rework: dungeon data client specific modules

- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/RequestList.lua
- LFGBulletinBoard/Tags.lua
- LFGBulletinBoard/dungeons/cata.lua
These commits connect a couple of components up to the new data modules introduced in #236.
Specifically:
-  `GGB.dungeonLevel` [6051d20](https://github.com/Vysci/LFG-Bulletin-Board/pull/237/commits/6051d20d837a11c9ddda758dacd47fda006a359e)
- `..DungeonName` tables for all expansions. [faa00a5](https://github.com/Vysci/LFG-Bulletin-Board/pull/237/commits/faa00a53ff8cc0f79a6341681ccabd0a879953fc)
- These tables had a list of pre sorted dungeon keys. Now generated using the `GetSortedDungeonKeys` functions in the new modules.
- The "Filters" configuration panels for all expansions. [1b41941](https://github.com/Vysci/LFG-Bulletin-Board/pull/237/commits/1b4194120ad0142d468197f4d9cde01d8aacf876) - [c1db615](https://github.com/Vysci/LFG-Bulletin-Board/pull/237/commits/c1db615777a3eaf7c7a8d5d33e0 …
> rework: Filter config panels hooked to new data modules

- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/changelog.txt
- LFGBulletinBoard/dungeons/cata.lua
Proceeds #237
These commits finish basic settings support for Cataclysm dungeons.
Additionally, disables the "Request List" tab in cataclysm clients while its made functional (todo)
**Note** - These changes do not add any preset tags for the new dungeons but adds the edit boxes in the config panels so that users can add their own patterns. Default English tags for Cataclysm dungeons are included in a future PR.
**images**
> feature: preliminary settings support for Cataclysm dungeons

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/GroupList.lua
- LFGBulletinBoard/LfgToolList.lua
- LFGBulletinBoard/LibGPIToolBox.lua
- LFGBulletinBoard/RequestList.lua
- LFGBulletinBoard/changelog.txt
Included in these commits:
- Headers will now use a highlighted text on mouseover
- Request entries will show a highlight texture on mouseover
These commits include annotations for cleanups for the `CreateHeader` and `CreateItem` functions. Goal is to eventually generalize these functions for each tab (when the LFG Tool tab gets fixed)
**images**
before/after (Top => Bottom)
> feature: add UI indicators for moused-over entries and headers

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/LibGPIToolBox.lua
- LFGBulletinBoard/Localization.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/Tags.lua
- LFGBulletinBoard/changelog.txt
- LFGBulletinBoard/dungeons/cata.lua
This PR adds basic locale support for esES, esMX, and ptBR to the addon.
**Related issues**:
- #191
**Notes**:
- It **does not** add any preset search patterns for categorizing chat messages, those are required to be contributed as i dont play on these locales.
- `esES` and `esMX` share a table for preset atm, open to splitting it if requested.
- Not all addon configuration display strings are translated, only the few which had usable alternatives in client global tables (see available strings here [wago.tools/db2/GlobalStrings](https://wago.tools/db2/GlobalStrings?build=4.4.0.54986&filter[Flags]=1|3))
-  Previously manually translated display strings in `Localization.lua` **will not** be used over the game provided translations in global strings for client locales that had them **for …
> feature: extended locale support

- LFGBulletinBoard/LibGPIToolBox.lua
Request message links will not be expanded until clicked.
Fixes an issue where profession links would automatically open when hovered.
- #177
> hotfix: treat hyperlinks in request messages like chat hyperlinks

- LFGBulletinBoard/RequestList.lua
**images**
(search pattern: "heal")
before:
after:
> minor: `ResultsFilter` now prevents empty categories

- LFGBulletinBoard/GroupBulletinBoard.lua
**Related Issues**
- #241 
Fixes issue where scroll would randomly break when swapping between message display options.
Completely hides unused tabs instead of showing a disabled state
Note: scroll functionality should be tested again before re-adding the tabs and their frames.
> hotfix: Hide frames pertaining to currently unused tabs

- LFGBulletinBoard/GroupBulletinBoard.lua
**Related Issues**
- #247
**Note**: This only fixes the issue for newly created characters. For existing characters all you have to do is reorder the channels in the blizzard chat settings.
> fix: prevent new characters from joining lfg channel before others

- LFGBulletinBoard/Localization.lua
Related issues:
- #207 
Fixes an issue where the addon would join the wrong `LookingForGroup` channel on cataclysm clients.
For example, on french clients blizzard uses "RechercheDeGroupe" in cataclysm, but "RechercheGroupe" in classic.
Just noticed its also an issue on `esES` (but not `esMX`)
**images**
> fix: `LookingForGroup` localization missmatch between Cata and Classic

- LFGBulletinBoard/Options.lua
Previously, most changed options would only save after clicking the "close" button specifically.
- Tabbing between option categories now also saves changes.
**Note**: Still need to close/hide the options to see any changes on the bulletin board itself.
> fix: Save options anytime they are closed or hidden

- LFGBulletinBoard/CustomCategories.lua
- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/LibGPIOptions.lua
- LFGBulletinBoard/Localization.lua
- LFGBulletinBoard/Options.lua
- #179 
**Included in this PR**
- Support for user generated filters
- Settings panel for managing user generated filters
- includes: a Toggle, ability to rename, filter sorting, filter pattern editing
**Notes**
I think this can be used for the SoD specific categories as well in #213, I've set it up so that we just have to include it as a preset.
I tried to use the old options library from the original author but it had far too many constraints for building a more dynamic settings panel. 
@Vysci, I Recommend we move towards using a library like AceConfig, it allows for an "easier" building of settings, but more importantly it does a good job at validating and maintaining state between options and their saved variable values. That would fix alot of the "requires reload" …
> feat: Custom User Filters Support

- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/Tags.lua
- LFGBulletinBoard/dungeons/cata.lua
- #253 
**In this PR**
- All the logic specific to seasonal dungeon events is now self contained and colocated in `/dungeons/cata.lua`.
- Adds `Tags.lua` entries for Midsummer and Valentines events.
- Decouple any seasonal dungeon stuff from classic era code
> fix: move `GBB.Seasonal` dungeons into `/dungeons/cata.lua`

- LFGBulletinBoard/CustomCategories.lua
- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/Tags.lua
These changes are related to the feature added in #250. Users can now edit the client specific filters, `RDF`,`BLOOD`,and `INCUR`, without having to edit the main lua file. Useful for users on non english locales.
Fixes: 
- added "gammas" as part of RDF english tags (#193)
- the "Defaults"/restore preset button no longer overrides custom search patterns.
- Pressing "escape" now properly closes custom filter related popup menus
> refactor: move `RDF` `BLOOD` and `INCUR` filters to `CustomCategories.lua`

- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/Tags.lua
- LFGBulletinBoard/changelog.txt
Doc updates in prep for 3.32.
**Tot4W tags hotfix adds**:   
- english: `to4w`, `t4w`, `tot4w`.
- french: `t4v`, `t4w`.
- german: `td4w`, `t4w`.
> hotfix: improve Tot4W tags, update `.toc` and `changelog.txt`

- LFGBulletinBoard/GroupBulletinBoard.lua
Fixing lua errors that occur in the case CustomFilters hasn't been initialized.
> Fixing CustomFilters errors

- LFGBulletinBoard/CustomCategories.lua
- LFGBulletinBoard/GroupBulletinBoard.lua
In attempts to keep any non "read" action to saved variables pertaining to custom filters local to its "module's" file
Context:
- #258
- #259
> minor: move `CustomFilters` saved var initialization to `CustomCategories.lua`

- LFGBulletinBoard/Options.lua
Encountered after deleting my saved vars file testing #258. Very minor issue only likely encountered by new users with no saved vars at all.
- Issue was caused by the `TagsEnglish`, `TagsGerman`, etc. saved var values not having been initialized before first call to `GBB.UpdateAdditionalFiltersPanel()` causing the following snippet to always return `nil` and the corresponding editboxes not being shown. 
```lua
local isLocaleUserEnabled = function(locale)
local enabledLocales = {
enGB = GroupBulletinBoardDB.TagsEnglish,
enUS = GroupBulletinBoardDB.TagsEnglish,
deDE = GroupBulletinBoardDB.TagsGerman,
ruRU = GroupBulletinBoardDB.TagsRussian,
frFR = GroupBulletinBoardDB.TagsFrench,
zhTW = GroupBulletinBoardDB.TagsZhtw,
zhCN = GroupBulletinBoardDB.TagsZhcn,
esES = …
```
> bugfix: "Additional Filters" ui bug on first load

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/LibGPIToolBox.lua
- LFGBulletinBoard/changelog.txt
Related Issue:
- #264
Added some additional LuaLS type annotations to cover the case that missed the initial bug.
> fix: indexing undefined global in `Event_CHAT_MSG_SYSTEM` event handler

- LFGBulletinBoard/CustomCategories.lua
- LFGBulletinBoard/GroupBulletinBoard.lua
- #262
Reworked `AddCustomFilterTags` to `SyncCustomFilterTags` which now removes tags for any deleted custom filter keys and adds any enabled custom filter's tags as well.
> fix: lua errors for missing tags after deleting a custom category

- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/changelog.txt
toc interface version bump for new client: 1.15.2 -> 1.15.3
Also minor changelog entry styling for 3.32 release
> chore: `.toc` game version update

- LFGBulletinBoard/LfgToolList.lua
- LFGBulletinBoard/LibGPIOptions.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/RequestList.lua
- Re-implemented the `InterfaceOptions_AddCategory` function locally for when the deprecated code is eventually removed from blizzard source.
- Removed some ui elements that would previously open to specific panels.
**Notes:** 
- Blizzard moved to the 10.0 UI in classic clients last year and the `OpenToCategory` method no longer opens to subcategories. See https://github.com/Stanzilla/WoWUIBugs/issues/285
- The addon up to this point previously "OnCancel", "OnOkay" and "OnDefault" functions for updating the settings panels but blizzard now uses a scheme with "OnCommit"/"OnRefresh"/"OnDefault"
> refactor: move from blizzard deprecated `InterfaceOptions_AddCategory` to `Settings.RegisterCanvasLayoutCategory` 

- LFGBulletinBoard/CustomCategories.lua
- LFGBulletinBoard/LibGPIOptions.lua
- LFGBulletinBoard/Options.lua
- Checkbox filters now save without having to `close` the options panel.
- The `.func` field from `ChatConfigCheckButtonTemplate` is used to trigger the savedVar handle's OnChange callbacks
- shift+right click will now reset a checkbox back to its default value
- resolves #57
- resolves #147
**Images**:
> refactor: migrate `CheckButton` options widgets to use `SavedVarRegistry`

- LFGBulletinBoard/LibGPIOptions.lua
- color picker now dynamically updates the saved variable when the color is changed
- new color will be saved when the "Okay" button in the ColorPickerFrame is clicked
- shift+right clicking a swatch resets it to the default color
**Images**:
> refactor: migrate color picker widgets to use `SavedVarRegistry`

- LFGBulletinBoard/LibGPIOptions.lua
- LFGBulletinBoard/Options.lua
- Moved from using `InputBoxTemplate` to `InputBoxInstructionsTemplate` 
- Adds a `.Instructions` fontstring which can manage the placeholder text when the editbox is empty.
- Input is now saved upon pressing "Enter" key. 
- This also updates the `GBB.tagList` on enter pressed (only for the dungeon editboxes) 
- Added text indicators for this change in the relevant options panels.
- #123 
**Images**:
> refactor: migrate `EditBox` widgets to new `SavedVarRegistry` management system

- LFGBulletinBoard/LibGPIOptions.lua
- LFGBulletinBoard/Options.lua
I've modified the input for the list that can be passed to `AddDropdownToCurrentFrame`.
It now accept a table with button info directly for being able to display different text than what the inner button `.value` should be.
- Removed "reload required" text from font size setting
**Images**:
> refactor: migrate `DropDownMenu` to utilize `SavedVarRegistry`

- LFGBulletinBoard/LibGPIOptions.lua
- LFGBulletinBoard/Options.lua
- clean up public functions for frames not connected with the the `SavedVarRegistry`.
- includes variable renames, formatting changes, etc.
- Remove post-refactor dead code. 
- Most of this commented code was related to syncing widgets to saved vars when the `close` button was pressed.
> refactor: post rework cleanup of `LibGPIOptions.lua`

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/Options.lua
- moved around local helpers & public interfacing options to be colocated
- the hack around issues #200, #147, #57, has been removed (no longer needed)
- connected a couple of edge case setting updates to the new SavedVar system
- `EnableGroup` toggling the approriate tabs.
- `TimeOut` duration clamped above 60
- `ChatStyle`/`CompactStyle` mutual exclusivity
> refactor: update of `Options.lua` to take advantage new `SavedVarRegistry`

- LFGBulletinBoard/dungeons/classic.lua
Uses ID from https://wago.tools/db2/Map?build=1.15.3.55563&filter[MapName_lang]=Demon&page=1 for the translation.
**Images**:
Build checked on:
> hotfix: add translations for "Demon Fall Canyon" dungeon name

- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/RequestList.lua
- LFGBulletinBoard/dungeons/classic.lua
- #281
- #288
- #289
**Changes**:
- `DFC` does not need to be have its dungeonSort index set to a decimal value. 
- I believe the motivation for fractional dungeonSort values was so that the associated key would not get iterated over in any of the simple integer loops that used the `MAXDUNGEON` related variables.
- `DFC`'s name is defined in `dungeons/classic.lua` and does not need to be set in DefaultEnGB table
- `DFC` does not need to be disambiguated from `DM2` and `DM`.
> fix: cleanup unnecessary edge case inclusions of `DFC`

- LFGBulletinBoard/LibGPIOptions.lua
- LFGBulletinBoard/Options.lua
This is a re-implementation of #275, following @Vysci's reverts in #278 & #279
Id like some more info surrounding the issues you encountered that lead to the reversion, so i know at what point to debug. 
I've gone and checked the state of the addon in commits in #275, #276, #277 on SoD trying to find an error but no luck. 
I havent changed any code from these commits that i'm testing vs the original PR commits (rest of PR's will be submitted after this one), so any errors you encountered would still be in here, thats why i ask.
> revert: re-add "migrate `DropDownMenu` to utilize `SavedVarRegistry`"

- LFGBulletinBoard/Options.lua
**Related Issues:**
- https://legacy.curseforge.com/wow/addons/lfg-group-finder-bulletin-board?comment=674
- https://legacy.curseforge.com/wow/addons/lfg-group-finder-bulletin-board?comment=677
Adds some logic so that both these options cannot be selected at the same time. Selecting both makes no sense as you're asking for a dungeon that is both heroic and normal.
Previous to this fix, selecting both options would result in empty bulletin boards since no dungeon listing can be classified as both heroic and normal.
> hotfix: add mutual exclusion logic for `HeroicOnly` and `NormalOnly` options

- LFGBulletinBoard/CustomCategories.lua
- LFGBulletinBoard/LibGPIOptions.lua
- LFGBulletinBoard/Options.lua
`UIPanelScrollFrameTemplate` is considered deprecated and was replaced with `WowScrollBox` templates.
We should move away before blizzard deletes the deprecated file (if they ever do).
It pretty much behaves like the old one, theres a scrollChild that you parent your scrollable elements to, instead now the scrollChild will auto size itself based on its content. Similar method will be used when migrating the `RequestList` to `WowScrollBox` in the future.
**Sample Image:**
**Tested On**
> rework: migrate from deprecated `UIPanelScrollFrameTemplate` to `WowScrollBox` in the settings panels

- LFGBulletinBoard/Options.lua
A proper fix was added in #277
> minor: remove redundant cleanup code in `GBB.OptionsUpdate`

- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/Tags.lua
- LFGBulletinBoard/changelog.txt
- LFGBulletinBoard/dungeons/classic.lua
Adding world bosses to SoD. Not adding to era because LFG world bosses is not how it works. 
Decided to add it in 1 category due to the fact people are often searching for "world bosses", so it can apply to multiple categories which is not something that this add-on is capable of handling. It would also end up with a lot of duplicate entries as more bosses are added. Can revisit it in the future
Also enabling the filters to default to being toggled on for current expansion as there has been a lot of ask for this and confusion on why they aren't seeing dungeons
> Adding world bosses

- LFGBulletinBoard/LibGPIMinimapButton.lua
- LFGBulletinBoard/Localization.lua
- LFGBulletinBoard/Options.lua
- #301
**In this PR**
- adds a `UseLibDBIcon` option as **"Manage minimap button using LibDBIcon"**. 
- only available when the user has `LibDBIcon-1.0` installed.
- disabled by default, unless the user currently has the **"Minimize minimap button distance"** (`lockDistance`) option, which attaches the button to the edge of minimap when enabled.
- Better aligns our minimap button with LibDBIcon-1.0 buttons if any exist (notably when the `UseLibDBIcon` is **not** enabled).
- Minimap button can no longer be dragged off the right side of the screen when not anchored to the Minimap.
- **note**: If the minimap button is managed by the `LibDBIcon-1.0`, it **cannot** be dragged away from the edge of the minimap at all.
- Renamed button frame from `"Lib_GPI_Minimap_"..TOCNAME` …
> [feat][hotfix]: Improved compatibility with `LibDBIcon-1.0` minimap buttons

- LFGBulletinBoard/LibGPIMinimapButton.lua
Button will now reposition itself along the edge of the minimap when the `lockDistance` option is toggled.
- This interaction only applies when *not using* the "Manage minimap using LibDBIcon" (`UseLibDBIcon`) options
> [feat][minor]: Add reactivity to the minimap button when toggling the `lockDistance` option

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/Options.lua
Whenever the icon is in `LibDBIcon` mode, its bound to the perimeter of the minimap, which is the same effect of the `lockDistance` option.
In order to prevent confusion, the `lockDistance` option is now disabled (as in grayed and unable to be toggled) whenever the `UseLibDBIcon` option is toggled on.
> [minor][ui]: *disables* the the `lockDistance` option whenever the `UseLibDBIcon` option is enabled

- LFGBulletinBoard/GroupBulletinBoard.lua
Fixes edge case when `LibDBIcon` is no longer available after having previously been available and used by the addon
> [hotfix]: fix disabled button state on minimap dropdown menu

- LFGBulletinBoard/LibGPIOptions.lua
Seems like old options frames were removed as of 1.15.4
Previous reworks have already removed other related deprecated frames
> [fix]: remove reference to fully deprecated frame `InterfaceOptionsFramePanelContainer`

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/LibGPIOptions.lua
- LFGBulletinBoard/Localization.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/RequestList.lua
- not having filters selected seems to trip up alot of users into thinking the addon is broken.
- clicking the message will open up the filter settings.
**images**:
> [feat]: adds a message notifying user when no filters are selected

- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/changelog.txt
Not sure the respective patches are dropping. I will likely do client specific releases of `3.38` if cata/era dont share a patch day.
> [chore]: update changelog and `toc` version for 1.15.4/4.4.1

- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/Tags.lua
- LFGBulletinBoard/changelog.txt
- adds `thunderan` and `thunderaan` keywords for the new Crystal Veil "raid" (its an instanced boss like other world bosses), added in SoD phase 5 .
- opted to just adding additional tags to the "World Bosses" category as opposed to its own "The Crystal Veil" dungeon category.
> [hotfix]: Add new SoD world boss to `WB` category tags

- LFGBulletinBoard/changelog.txt
Caused by blizz having staggered client releases 1.15.4/4.4.1 and our monorepo style setup.
> [chore]: update changelog's existing `v3.39` release notes for Cata release

- LFGBulletinBoard/GroupBulletinBoard.xml
- now expected to use the inheritable `BackdropTemplate` with a standard `Frame` element.
note: I commented it out completely at some point and the addon was still functional. I suspect these frames are not actually doing anything atm. Will look at trimming in the future.
> [hotfix]: migrate away from `Backdrop` xml element removed in 1.15.5

- LFGBulletinBoard/LfgToolList.lua
- LFGBulletinBoard/Localization.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/RequestList.lua
relates issues:
- #324 
Current replacements added are:
- `%level` - player level
- `%class` - player class
- `%role` - role selected in addon filters panel
- `%dungeon` - name of dungeon/activity
> [hotfix][rework]: Add text replacements for the `alt-click` whisper feature

- LFGBulletinBoard/RequestList.lua
The `Localization.lua` files logic auto inserts an empty string value (`""`) for the `CustomLocales` table. Might be worth to keep these entries `nil` instead in the future.
> [hotfix]: use proper fallback for empty `CustomLocales.JOIN_REQUEST_MESSAGE` strings

- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/Localization.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/Tags.lua
- LFGBulletinBoard/dungeons/classic.lua
- The World Bosses category `WB`  which was used as catch-all for the first 2 world bosses released on SoD, has been removed.
- in its place `AZGS` and `KAZK` have been added to the propper data tables. 
- Adds the new world boss category comming for sod phase 6
- `NMG` - for "Nightmare grove", (emerald dragons)
-  These may need to be seperated out in the future for regular non-sod era.
- Added a new entry to the Addons `Enum.DungeonType` table for `WorldBosses`.
- Note: The `GetActivityInfoTable` API identifies the SoD World Bosses as `DungeonType.Raid` so these have to be overridden to our spoofed Enum for the World Bosses.
- Includes a "World Bosses" header in the settings panel for classic filters
- ![WowClassic_PNVr9TLBS3](https://github.com/user-attachments/assets/cd …
> [refactor]: seperate out World Bosses from Raids for classic

- LFGBulletinBoard/Localization.lua
- LFGBulletinBoard/dungeons/classic.lua
The game uses the zone name for these, but community normally identifies them by the boss name.
May need to add the emerald dragons bosses in the future, however for SoD they will all be in the same instance so i kept that one as the zone name "Nightmare Grove"
> [minor]: change the display name for world bosses

- LFGBulletinBoard/GroupBulletinBoard.lua
If ever requested can add the option to include the rank back in.
**note:** the `EnableGuild` option should either removed altogether, or at least only limited to addon created tooltips in the future.
fixes #329
> [minor]: Remove guild rank from the `EnableGuild` tooltip

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/GroupBulletinBoard.xml
- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/LfgToolList.lua
- LFGBulletinBoard/RequestList.lua
- LFGBulletinBoard/dungeons/classic.lua
**Related Issues**: 
- #323 
This pull request includes significant changes to the `LFGToolList.lua` module including:
- removing old scroll and entry frames and integrating new ones
- updating the requestList generation/parsing to respect the activityID system.
- addressing limitations around the `C_LFGList.Search` API
* [`LFGBulletinBoard/GroupBulletinBoard.lua`](diffhunk://#diff-93cc48d022994422e1d92249731e5fafce9a04ed82e7da18358109de568a7d1aL323-L335): Removed old LFG frame resizing and refresh button functions (`GBB.ResizeFrameList`, `GBB.BtnRefresh`). [[1]](diffhunk://#diff-93cc48d022994422e1d92249731e5fafce9a04ed82e7da18358109de568a7d1aL323-L335) [[2]](diffhunk://#diff-93cc48d022994422e1d92249731e5fafce9a04ed82e7da18358109de568a7d1aL368-L371)
* …
> [Feature][Era]: Support Group Finder tool on Anniversary/SoD realms. 

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/LibGPIOptions.lua
- LFGBulletinBoard/Localization.lua
- LFGBulletinBoard/Options.lua
- will gray out sub-options when the parent option is disabled basically.    
- should help improve the eye-soreness of the addon main settings panel.
- additionally, reintroduces option to include guild rank in guild tooltip.
**related issues**
- #333 
**images**
> [feat][ui]: disable child option widgets when parent setting is disabled

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/LfgToolList.lua
- LFGBulletinBoard/RequestList.lua
**[feat][refactor]: settings button now toggles a simple dropdown**
- allows easier access to the filter settings
**[hotfix]: sync folded/collapsed headers between chat and tool requests**
- bulletin board headers folded on the chat requests tab should remain folded when switching to the tool requests tab
- this hacky solution can be removed whenever i move the chat requests tab over to the same scrollbox/dataprovider api.
**[hotfix]: require `name` when generating request list entries for `LFGTool`**
- prevents "Unknown" players from appearing in the request list
**[feat]: share player level info from Tool Request with Chat requests**
**[dev][minor]: use named constants for data provider method arguments**
**[bugfix]: correct template name for "WowScrollBoxList"**
**[perf]: cleanup …
> [misc][hotfix] Minor updates and LFGTool ui nit hotfixes

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/GroupList.lua
- LFGBulletinBoard/LfgToolList.lua
- LFGBulletinBoard/LibGPIToolBox.lua
**[refactor]: use C_LFGList API to determine available LFGTool categories**
Instead of manually enabling/disabling categories from the hardcoded table.
- enum table reflecting possible values added for source readability.
- note: the `C_LFGList.GetAvailableCategories` api can return an empty table early in the load process.
- todo: instead of rebuilding the menu every `OnShow` for the bulletin board, rebuild only when C_LFGList.GetAvailableCategories returns new values
**[refactor][dev]: set up enumerated table for managing the different Tabs**
- named them ChatRequests, RecentPlayers, and LFGTool (for the RequestList, GroupList, and LfgToolList respectively)
**[refactor]: disable `LFGTool` for characters who dont have access to it yet**
- note: "disabled" as in; its still is visible and …
> [refactor]: more minor ui updates around LFGTool

- LFGBulletinBoard/LfgToolList.lua
This change allows showing/hiding dungeon entries in the `LFGTool`'s Scrollbox as soon as they are toggled on/off in the settings.
> [hotfix]: update LFGTool view entries when dungeon filter settings change

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/LfgToolList.lua
- more permanently addresses a previous hotfix around sharing collapsed headers between the LFGTool and Chat Request tabs in #338 
- fixes an issue where when the addon board was closed and re-oppend while in the LFGtool tab, it would show stale entries.
> [refactor][fix]: update `LFGTool` board whenever its container frame is shown

- LFGBulletinBoard/LfgToolList.lua
Fixes an issue when not using the "Dont Truncate Messages" options.
The "role" textures for LFGTool entries would occasionally show up in erroneous positions, such as overlapping with other entries. (see image)
> [fix][ui]: fix a minor UI issue in LFGTool entry frames

- LFGBulletinBoard/Chat.lua
- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/GroupBulletinBoard.xml
- LFGBulletinBoard/LfgToolList.lua
- LFGBulletinBoard/LibGPIOptions.lua
- LFGBulletinBoard/LibGPIToolBox.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/RequestList.lua
**[refactor]: migrate settings panel dropdowns to the new dropdown api**
- removes usage of deprecated UIDropDownMenu api
- this change should prevent any settings panel dropdowns from tainting ui
**[refactor]: migrate announcement channel selection dropdown to new API**
- similar to settings panel changes.
**[refactor][hotfix]: implement `TaintLess.xml` style cleanup for touched DropDownList buttons**
- Implementation of fixes mentioned in #344 
- This prevents *most* taint errors while allowing us use the `UIDropDownMenu`.
- This is a temporary solution to rewriting the whole `Tool.CreatePopup` system to support the new menuGenerator APIs.
- note: the `PopupDyanmic` frame is hard to re-create using the new API's because they dont support Right Clicks.
> [fix][refactors]: Fix taint issues related `UIDropDownMenu` api usage

- LFGBulletinBoard/dungeons/classic.lua
Reuses already defined tags for key `KARA` from other game versions of Karazhan.
Uses `ActivityID=1693`
Data for  `C_LFGList.GetActivityInfoTable(1693)` can be found @ https://wago.tools/db2/GroupFinderActivity?build=1.15.6.58866&sort[ID]=desc
> [hotfix][feat]: add Karazhan Crypts category for SoD realms

- LFGBulletinBoard/dungeons/classic.lua
- This change should allow the addon to properly categorize Naxx (and possibly other dungeons) in the Tool Requests tab even if the underlying `activityID` use by `C_LFGList` is different from what we have hardcoded
- In anticipation of a new `activityID` being hotfixed in for Naxx on SoD. Similar to how MC/BWL/AQ got new activityIDs.
> [minor][refactor]: add name-matching fallback for `GetDungeonKeyByID`

- LFGBulletinBoard/Tags.lua
- LFGBulletinBoard/dungeons/classic.lua
**[hotfix]: fix incorrect activityIDs for AQ20 and AQ40 in SoD**
- they were simply swapped, so AQ20 was showing as AQ40 and vice versa
**[refactor]: move SoD specific tags to conditional block**
- better organization of tags and prevents leaks to other clients.
- adds additional "SoD only" tags to `AQ20`
> [hotifx][refactor]: fix issues with AQ being categorized improppely in SoD

- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/RequestList.lua
- adds dropdown in main settings panel to select between available sound output channels for the Sound Notification setting
- ![image](https://github.com/user-attachments/assets/c75c4d8b-5041-4e48-b0fc-d84341d3d49b)
- #54
> [feat]: support for changing sound notification output channel

- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/Tags.lua
- LFGBulletinBoard/changelog.txt
- LFGBulletinBoard/dungeons/cata.lua
- adds Dragon Soul to the Cataclysm raids list
- fixes some empty string returns in dungeon data generation stage caused by updates to db2 tables.
-  toc and changelog updates for 3.43 release
> [hotfix]: updates for Cataclysm patch `4.4.2`

- LFGBulletinBoard/LfgToolList.lua
- seems to be happening only on some resolutions
**image of bug**
> [minor][ui]: fix member levels being truncated in `LFGTool` tooltip

- LFGBulletinBoard/Tags.lua
- LFGBulletinBoard/dungeons/classic.lua
- uses a spoofed ActivityID with localized names ripped from `GetRealZoneText`
- allows the 'match by dungeon name' to work in the `LFGTool`, even when we don't know the actual ActivityID that will be used by blizzard for this raid.
- adds basic english patterns of `"scarlet" "enclave" "se"`
- users may see false grouping of messages containing "scarlet" since it's a common word
> [feat]: add "Scarlet Enclave" SoD raid support

- LFGBulletinBoard/LibGPIToolBox.lua
- because `SetSelected` was called after `.Contents` was assigned. The` .Content`'s initial show state was set incorrectly.
> [hotfix]: fix bug in pr #363

- LFGBulletinBoard/LibGPIToolBox.lua
- uses SetPoint instead of AdjustPointsOffset method.
- remove now redundant setPoint
> [hotfix]: fix #366 - bug causing tab text to continually offset

- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/RequestList.lua
- LFGBulletinBoard/Tags.lua
**[minor]: Add sound effects to the bulletin board settings button dropdown**
**[fix]: additional criteria to handle tag string collision priorities**
- when initially implemented, tags would get priorizited by expansion only
- now prioritized by expansion > dungeon type (dungeon, raid, battleground) > max level.
- allows the "scarlet" tag to be used to for Scarlet Enclave (over Scarlet Monastery) on SoD builds
**hotfix: better distinguish dungeons from items in `TRADE` requests**
- should reduce the amount of "Scarlet" item in trade getting categorized as part of Scarlet Enclave
- before
- ![Discord_s6s6uTJ6T0](https://github.com/user-attachments/assets/9e934773-69c4-40e9-822c-e72391255959)
- after
- ![image](https://github.com/user-attachments/assets/80a19fd1-5a62-4181-be53-daf01fde728c) …
> [hotfix]: variety of small fixes mostly around Scarlet Enclave parsing

- LFGBulletinBoard/LibGPIToolBox.lua
- Trading off some space for time in `GBB.Tool.iMerge`
- For long messages the, `tContains` method checking for unique entries was making the `GetMessageWordList` method take longer than necessary.
- The new method instead uses a lookup to check for duplicates, which is faster for larger lists.
> [perf]: improve inner merge helper function

- LFGBulletinBoard/GroupBulletinBoard.xml
- LFGBulletinBoard/LfgToolList.lua
- LFGBulletinBoard/RequestList.lua
- Also trimmed down the amount of options.
- planning on re-adding them to the settings button _right-click_ version dropdown menu.
- #73 
**Images**:
BEFORE
AFTER
> [refactor]: use `Blizzard_Menu` for request Entry and Header popup menus

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/GroupBulletinBoard.xml
- LFGBulletinBoard/RequestList.lua
**[refactor]: clean up request entry frame implementation**
- moved to using a mixin style implementation
- clarified logic around sub-frame placements for the different layout modes
- using a reusable frame pool for the manage recycling frames
- goal is to make entry frame setup compatible with a WoWScrollBox in the future
- and flexible enough to be reused for LFGToolList in the future
**[refactor]: clean up request list header frame implementation**
- see commit message for request list entry frame refactors
> [refactor]: tidy `RequestList.lua` header and entry frame implementations

- LFGBulletinBoard/CustomCategories.lua
- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/LfgToolList.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/RequestList.lua
- LFGBulletinBoard/Tags.lua
method renames:
- `GBB.GetDungeons` -> `getRequestMessageCategories`
- `GBB.ParseMessage` -> `parseMessageForRequestList`
- `GBB.FoldAllDungeon` -> `foldAllHeaders`
- `GBB.UnfoldAllDungeon` -> `unfoldAllHeaders`
- `GBB.UpdateList` -> `GBB.ChatRequests.UpdateRequestList`
- `GBB.Clear` -> folded into `GBB.ChatRequests.UpdateRequestList`
- Moved handlers for `CHAT_MSG_` events, related to the request list, into `RequestList.lua`  for better colocation.
- Folded `GBB.Clear` into the new `UpdateRequestList` since it wasn't referenced outside of the file
- Move public accessible logic specific to the request list into a `ChatRequest` module within `GBB`
- cleans up the GBB namespace a bit.
> [refactor]: modularize & reorganize methods and references for `RequestList.lua`

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/LibGPIToolBox.lua
- fixes #381 
- making the board non interactive still keeps resizing behavior since the board position is intentionally still movable in that state.
> [fix]: locking the bulletin board now prevents resizing

- LFGBulletinBoard/CustomCategories.lua
- LFGBulletinBoard/Localization.lua
- LFGBulletinBoard/RequestList.lua
- option toggle accessed via a new settings button next to each custom filter's header
- fixes #382 
- ![image](https://github.com/user-attachments/assets/ff93c4aa-5a0b-4168-ab58-4bb320c6cb6b)
> [hotfix][feat]: Add option to bypass link disqualification for custom filter keywords

- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/Tags.lua
- was causing issue where all tags were being removed by the pruning logic in Tags.lua
> [hotfix]: assert client dungeon keys are loaded before needed in `Tags.lua`

- LFGBulletinBoard/CustomCategories.lua
- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/Localization.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/RequestList.lua
- LFGBulletinBoard/Tags.lua
- LFGBulletinBoard/dungeons/api.lua
- LFGBulletinBoard/dungeons/mists.lua
**[minor][mop]: minor addition to search patterns for Mists dungeons**
**[feat][mop]: add world boss filters**
- adds dedicated filters for Sha of Anger, Galleon, Nalak, Oondasta, and Ordos.
- doesnt add filter for Four Celestials from timeless isle as people dont premake groups for it.
**[feat]: add "Isolate Requests" option to custom/additional filters**
- enabling this option will make it so that messages with the declared keywords for that filter, will only be categorized under that filter in the bulletin board.
> [feat]: add "Isolate Requests" option and add MoP World Bosses
