- LFGBulletinBoard/changelog.txt
> Restoring changelog

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/RequestList.lua
Detects if running vanilla or tbc, and enables/disabled features based on game version
> Added detection of vanilla or tbc

- LFGBulletinBoard/LibGPIToolBox.lua
> Fix error on who from context menu

- LFGBulletinBoard/Localization.lua
- LFGBulletinBoard/RequestList.lua
> implement click invite

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/Localization.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/RequestList.lua
- LFGBulletinBoard/Tags.lua
- LFGBulletinBoard/bindings.xml
- LFGBulletinBoard/changelog.txt
Fixed "hc" not being part of heroic filtering. Also refactored which allows it to be modified under search pattern. Made bindings.xml be under addon category
> Refactor of heroic filtering

- LFGBulletinBoard/GroupBulletinBoard.lua
Reverts Vysci/LFG-Bulletin-Board#48
> Revert "Add "/lfg" as an intuitive shorthand to open the GBB frame."

- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/Localization.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/changelog.txt
Fixed a crash that occurs when localization was used. Also fixed localization not actually working
> Fixing localization and crash

- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/Tags.lua
- LFGBulletinBoard/changelog.txt
> Added support for arena

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/GroupList.lua
- LFGBulletinBoard/RequestList.lua
> Adding icon for past players

- LFGBulletinBoard/GroupBulletinBoard.lua
Reverts Vysci/LFG-Bulletin-Board#105
> Revert "Allowing heroic dungeons when filtering by level"

- LFGBulletinBoard/RequestList.lua
Integrates the WarcraftLogs data from the LogTracker-Addon into the LFG Board Tooltips. ( https://www.curseforge.com/wow/addons/logtracker )
> Integration with LogTracker Addon for Tooltips

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/RequestList.lua
Using this addon on large pop servers like Firemaw makes the game lag like crazy (Issue #137), so I made some performance updates to throttle the message parsing and request list update.
I tried keeping to the existing naming conventions and code style :)
> Performance updates to reduce UI lag

- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/RequestList.lua
Was defaulting to vanilla version, removed the whole versioning thing
> Fixed TBC content not showing up

- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/LfgToolList.lua
- LFGBulletinBoard/changelog.txt
- Added auto refresh for lfg tool
- Semi fixed add-on exploding on custom
- BB should be honoring users selected lfg tool category unless it's not set
> auto refresh plus fixes

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/LibGPIOptions.lua
- LFGBulletinBoard/LibGPIToolBox.lua
- LFGBulletinBoard/changelog.txt
Uldar patch changed some functions, hopefully this fixes all of it
> Fixing Lua Errors

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/LibGPIToolBox.lua
- LFGBulletinBoard/RequestList.lua
- LFGBulletinBoard/changelog.txt
I have virtually no experience with LUA, but these changes have corrected all of the errors I was experiencing in Classic Era.
I've also added a few if statements to disable functionality based on game version that isn't available in Classic Era, but is available in WotLK+.
> Update for Classic Era 1.14.4

- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/LfgToolList.lua
I think the new patch is throwing errors now in such scenarios, so need to check for null now. I tested it and this works.
> Update for 3.4.3

- README.md
> nit: README.md reformat

- LFGBulletinBoard/Localization.lua
> bugfix: Fix to french `lfg_channel` localization

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/GroupBulletinBoard.xml
- LFGBulletinBoard/RequestList.lua
This is the implementation for the solution suggested in #205
Might also help alleviate problems like the one mentioned in #203 
**Notes**
Ive only used this addon in classic era (1.15.2) and i believe the addon only utilizes the `Request` tab in that client, and so i've only implemented the filtering for the request list.
> feature: Add a search box to filter request list entries.

- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/LfgToolList.lua
- LFGBulletinBoard/RequestList.lua
- LFGBulletinBoard/changelog.txt
This is the fix for when we try to sort and while a and b exists one of them might not exists in GBB.dungeonSort
> fixing errors when sorting

- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/RequestList.lua
- #201 
Here's with the option turned on
And turned off
> Fix "Combine sub-dungeon" option

- LFGBulletinBoard/LfgToolList.lua
- LFGBulletinBoard/RequestList.lua
- LFGBulletinBoard/Tags.lua
- #214 
- https://legacy.curseforge.com/wow/addons/lfg-group-finder-bulletin-board/?comment=619
> Remove unused dungeon tags for vanilla clients

- LFGBulletinBoard/RequestList.lua
minor, but helps declutter to board by making more room for the actual message
> feat: remove "[N]" and "[H]" columns in classic era.

- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/RequestList.lua
- #232
[01ab065] fixes bug no.3 in #232
[d787f1d] fixes bug no.1&2 in #232
> Fix: "show fixed requests per dungeon" option cleanup

- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/changelog.txt
No issues from the ~2k alpha downloads
> docs: update `changelog.txt` and `.toc`

- LFGBulletinBoard/CustomCategories.lua
- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/LfgToolList.lua
- LFGBulletinBoard/LibGPIOptions.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/RequestList.lua
- Cleanup in preparation for refactors to this `LibGPIOptions.lua` "library" file. Goal is to implement better system for syncing widgets to saved variables.
- No behavior changes included in this commit only renaming and commenting. 
- `Options` has been renamed to `OptionsBuilder` to better suit its purpose/usage.
> minor: reword and annotate interface functions for `LibGPIOptions.lua`

- LFGBulletinBoard/LibGPIOptions.lua
Goal is to allow checkboxes, editboxes, dropdowns, etc to modify saved variabless without having to properly close the options window to update changes as well as dynamically affect any other widgets that are hook to the same saved variables
- Allows the programmer to get a handle (`GetHandle`) to saved variable given its database and variable name.
- Handle has `SetValue` and `GetValue` methods used to update or check the value of the handles saved var.
- Handles are unique based on the database and variable name passed to `GetHandle`.
- Handles have a table of "OnUpdate" hooks which are ran when the saved value is changed. **note, only fires on changes values**
A helper function `RegisterFrameWithSavedVar`, and mixin `RegisteredFrameMixin` are provided to manage …
> feat: scaffold out `SavedVarRegistry` system for syncing frames to `SavedVariables` values

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/Options.lua
Reverts Vysci/LFG-Bulletin-Board#277
Reverting it as it's causing errors in SoD
> Revert "refactor: update of `Options.lua` to take advantage new `SavedVarRegistry`"

- LFGBulletinBoard/CustomCategories.lua
- LFGBulletinBoard/Dungeons.lua
- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/LICENSE
- LFGBulletinBoard/LibGPIOptions.lua
- LFGBulletinBoard/Options.lua
- LFGBulletinBoard/README.md
- LFGBulletinBoard/RequestList.lua
- LFGBulletinBoard/Tags.lua
- LFGBulletinBoard/changelog.txt
- LFGBulletinBoard/dungeons/classic.lua
SoD has a new event and a new dungeon
> Adding Demon Fall Canyon and BRM Event

- LFGBulletinBoard/LibGPIToolBox.lua
> fix: sync dynamic popup checkboxes with options panel

- LFGBulletinBoard/LibGPIOptions.lua
- LFGBulletinBoard/Options.lua
A re-merge of reverted PR #276 following reversion in #279
> revert: re-add "post rework cleanup of `LibGPIOptions.lua`"

- LFGBulletinBoard/GroupBulletinBoard.lua
- LFGBulletinBoard/Options.lua
Re-adding of pr #277 following reversion in #279
This was the last of the reverted commits.  No Errors encountered.
**Tested Clients**:
> revert: readd "minor cleanup of `Options.lua` following the new SavedVar system"

- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/changelog.txt
> chore: update `toc` and `changelog.txt`

- LFGBulletinBoard/GroupBulletinBoard.lua
- cleaned up debugging output for `GBB.CreateTagList` around duplicate patterns
- general formatting and type annotations for LuaLS
- moved to using one of the `/dungeons/{expansion}` API's for generating a dungeon list
- Added priority system for colliding/duplicate patterns for different keys 
- dungeons will have priority over any "Custom Filter" tags if there any shared one found.
- priority system can be expanded to use the associated `DungeonType` or dungeon level range.
**Note**. This is a bandage solution until a better system for the taglist is implemented that would allow assigning multiple keys to a single pattern
**Related Issues**
- #299 
**images**:
before 
after
> [hotfix] prioritize dungeons from latest expansion on clashing tag patterns

- LFGBulletinBoard/Tags.lua
- LFGBulletinBoard/dungeons/classic.lua
Because this is new im moving it to it's own category
> moving crystal vale to seperate

- LFGBulletinBoard/dungeons/classic.lua
- As of 1.15.5 blizzard has added these SoD dungeons onto the [GroupFinderActivity.db2](https://wago.tools/db2/GroupFinderActivity?build=1.15.5.57638) table. 
- Stub for the future raid "Nightmare Grove" left commented out for now 
- Eventually, `WB` key should be dissolved into `AZGS` and `KAZK` as well   
- can then treat them like Scarlet Monestary or Dire Maul and have all world bosses be group-able into a single category.
> [refactor]: remove hacks used to spoof SoD specific dungeon info

- LFGBulletinBoard/LfgToolList.lua
- inserts a frame into the tooltip for the LFGList results that shows the group composition.
> [feat]: add group member info to the entry tooltips for `LFGToolList`

- LFGBulletinBoard/LfgToolList.lua
Fixes an issue where clicking the button would update the text match the collapsed state but wouldnt actually collapse its entries.
> [hotfix][minor]: fixes "Collapse" button toggle in LFGTool's header's popup menus

- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/changelog.txt
- update toc version for era
- added myself to contributors on toc
> [chore]: update changelog for v3.42

- LFGBulletinBoard/LfgToolList.lua
- previously ALL entries that didnt have a dungeon key were grouped under "MISC" header
- this change allows for grouping by activity name (useful for quests and zones category)
**before image**
**after image **
> [refactor]: categorize "MISC" entries by Activity Name where possible in `LFGTool`

- LFGBulletinBoard/LibGPIToolBox.lua
- fixed error in logic for level limits. changed comment wording.
> [hotfix]: minor changes to pr#359

- LFGBulletinBoard/LFGBulletinBoard.toc
- LFGBulletinBoard/changelog.txt
- README.md
will release it later shortly.
> [chore]: update changelog, readme, and toc v3.44

- LFGBulletinBoard/LfgToolList.lua
- LFGBulletinBoard/Localization.lua
- LFGBulletinBoard/RequestList.lua
**[feat]: Add "Dismiss Request" button to request entry context menus**
- related issue: #42 
**[feat]: add "Disable" dungeon filter button for header menus**
**Images**
> [feat]: additional dismisability options to context menus

- LFGBulletinBoard/dungeons/classic.lua
- patch released and the activityID is now in the game
> [minor]: remove manual data shim for Scarlet Enclave

- LFGBulletinBoard/RequestList.lua
- LFGBulletinBoard/Tags.lua
- fixes small bug with Dire Maul and Deadmines disambiguation wrt DMN
> [minor][bugfix]: additional tag "dmt" for Dire Maul North
